version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/loyalty_service
      - ./static:/loyalty/static
      - ./media:/loyalty/media
      - ./staticfiles:/loyalty/staticfiles
    ports:
      - "9006:9006"
    env_file:
      - .env.prod
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:9006"
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
